/// ISO 3166-1 alpha-2 → 中文国家/地区名称映射，以及国旗 Emoji 计算。
library;

const Map<String, String> _countryNames = {
  'CN': '中国大陆',
  'HK': '中国香港',
  'MO': '中国澳门',
  'TW': '中国台湾',
  'US': '美国',
  'JP': '日本',
  'KR': '韩国',
  'GB': '英国',
  'FR': '法国',
  'DE': '德国',
  'AU': '澳大利亚',
  'CA': '加拿大',
  'SG': '新加坡',
  'MY': '马来西亚',
  'TH': '泰国',
  'VN': '越南',
  'PH': '菲律宾',
  'ID': '印度尼西亚',
  'IN': '印度',
  'RU': '俄罗斯',
  'BR': '巴西',
  'MX': '墨西哥',
  'IT': '意大利',
  'ES': '西班牙',
  'NL': '荷兰',
  'SE': '瑞典',
  'NO': '挪威',
  'FI': '芬兰',
  'DK': '丹麦',
  'PL': '波兰',
  'TR': '土耳其',
  'AE': '阿联酋',
  'SA': '沙特阿拉伯',
  'IL': '以色列',
  'ZA': '南非',
  'NG': '尼日利亚',
  'EG': '埃及',
  'AR': '阿根廷',
  'CL': '智利',
  'CO': '哥伦比亚',
  'PE': '秘鲁',
  'NZ': '新西兰',
  'IE': '爱尔兰',
  'PT': '葡萄牙',
  'GR': '希腊',
  'CZ': '捷克',
  'HU': '匈牙利',
  'AT': '奥地利',
  'CH': '瑞士',
  'BE': '比利时',
  'UA': '乌克兰',
  'RO': '罗马尼亚',
  'BG': '保加利亚',
  'RS': '塞尔维亚',
  'HR': '克罗地亚',
  'SK': '斯洛伐克',
  'SI': '斯洛文尼亚',
  'LT': '立陶宛',
  'LV': '拉脱维亚',
  'EE': '爱沙尼亚',
  'LU': '卢森堡',
  'MT': '马耳他',
  'CY': '塞浦路斯',
  'IS': '冰岛',
  'QA': '卡塔尔',
  'KW': '科威特',
  'BH': '巴林',
  'OM': '阿曼',
  'JO': '约旦',
  'LB': '黎巴嫩',
  'IQ': '伊拉克',
  'IR': '伊朗',
  'PK': '巴基斯坦',
  'BD': '孟加拉国',
  'LK': '斯里兰卡',
  'NP': '尼泊尔',
  'MM': '缅甸',
  'KH': '柬埔寨',
  'LA': '老挝',
  'BN': '文莱',
  'MN': '蒙古',
  'KZ': '哈萨克斯坦',
  'UZ': '乌兹别克斯坦',
  'GE': '格鲁吉亚',
  'AM': '亚美尼亚',
  'AZ': '阿塞拜疆',
  'KE': '肯尼亚',
  'TZ': '坦桑尼亚',
  'GH': '加纳',
  'MA': '摩洛哥',
  'DZ': '阿尔及利亚',
  'TN': '突尼斯',
  'LY': '利比亚',
  'ET': '埃塞俄比亚',
  'VE': '委内瑞拉',
  'EC': '厄瓜多尔',
  'BO': '玻利维亚',
  'PY': '巴拉圭',
  'UY': '乌拉圭',
  'CR': '哥斯达黎加',
  'PA': '巴拿马',
  'CU': '古巴',
  'DO': '多米尼加',
  'GT': '危地马拉',
  'HN': '洪都拉斯',
  'NI': '尼加拉瓜',
  'SV': '萨尔瓦多',
};

/// 部分境外省/市行政区划的中文常用译名（IP 库通常返回英文）。
const Map<String, Map<String, String>> _adminTranslations = {
  'HK': {
    'central and western': '中西区',
    'wan chai': '湾仔区',
    'eastern': '东区',
    'southern': '南区',
    'yau tsim mong': '油尖旺区',
    'sham shui po': '深水埗区',
    'kowloon city': '九龙城区',
    'wong tai sin': '黄大仙区',
    'kwun tong': '观塘区',
    'kwai tsing': '葵青区',
    'tsuen wan': '荃湾区',
    'tuen mun': '屯门区',
    'yuen long': '元朗区',
    'north': '北区',
    'tai po': '大埔区',
    'sha tin': '沙田区',
    'sai kung': '西贡区',
    'islands': '离岛区',
  },
  'MO': {
    'macao': '澳门',
    'macau': '澳门',
    'taipa': '氹仔',
    'coloane': '路环',
    'cotai': '路氹城',
  },
  'TW': {
    'taipei': '台北市',
    'taipei city': '台北市',
    'new taipei': '新北市',
    'new taipei city': '新北市',
    'taoyuan': '桃园市',
    'taichung': '台中市',
    'tainan': '台南市',
    'kaohsiung': '高雄市',
    'keelung': '基隆市',
    'hsinchu': '新竹市',
    'chiayi': '嘉义市',
    'changhua': '彰化县',
    'yilan': '宜兰县',
    'hualien': '花莲县',
    'taitung': '台东县',
    'pingtung': '屏东县',
    'yunlin': '云林县',
    'nantou': '南投县',
    'miaoli': '苗栗县',
    'penghu': '澎湖县',
    'kinmen': '金门县',
    'lienchiang': '连江县',
    'zhongzheng': '中正区',
    'xinyi': '信义区',
    "da'an": '大安区',
    'songshan': '松山区',
    'wanhua': '万华区',
    'datong': '大同区',
    'shilin': '士林区',
    'beitou': '北投区',
    'neihu': '内湖区',
    'nangang': '南港区',
    'wenshan': '文山区',
  },
  'US': {
    'california': '加利福尼亚',
    'new york': '纽约',
    'texas': '得克萨斯',
    'washington': '华盛顿',
    'florida': '佛罗里达',
    'illinois': '伊利诺伊',
    'massachusetts': '马萨诸塞',
    'new jersey': '新泽西',
    'pennsylvania': '宾夕法尼亚',
  },
};

/// 根据国家代码返回中文名称；未知代码回退到 API 原文。
String countryNameOf(String code, {String? fallback}) {
  final value = _countryNames[code.toUpperCase()];
  if (value != null && value.isNotEmpty) return value;
  return fallback?.trim().isNotEmpty == true ? fallback!.trim() : code;
}

/// 国家代码 → 国旗 Emoji（区域指示符号）。
String countryFlag(String code) {
  final upper = code.toUpperCase();
  if (upper.length != 2 || !upper.contains(RegExp(r'^[A-Z]{2}$'))) {
    return '🌐';
  }
  final runes = upper.runes.map((r) => r + 0x1F1A5).toList();
  return String.fromCharCodes(runes);
}

/// 对行政区划字段做本地化；找不到映射时保持原文。
String? localizeAdminArea(String countryCode, String? raw) {
  if (raw == null || raw.trim().isEmpty) return null;
  final table = _adminTranslations[countryCode.toUpperCase()];
  if (table == null) return raw.trim();
  return table[raw.trim().toLowerCase()] ?? raw.trim();
}
